### ISSUE TITLE
icon request: vscode, slack, and githubdesktop 

### ISSUE THREAD

**Issue by BenWiseman** [EliverLara/candy-icons#122]
If it's not too much hassle, these fellas would look pretty good with aesthetic icons and are fairly popular.

**Comment by pXius** [comment]
+1 for all of them, and Teams 

Thanks!

**Comment by Ahuahuachi** [comment]
vscode already exist, but the app has the icon path hardcoded in the `.desktop` files.

I use Kubuntu, there what I did was to edit both files `/usr/share/applications/code.desktop` and `/usr/share/applications/code-url-handler.desktop`.
Replaced the `Icon=/usr/share/pixmaps/com.visualstudio.code.png` for `Icon=code`.

Slack and Teams may be the same problem, because the icons are there also.

**Comment by EliverLara** [comment]
github-desktop icon has been added
