### ISSUE TITLE
(Tutanota Desktop) Minimised Icon Remains Unchanged

### ISSUE THREAD

**Issue by ghost** [EliverLara/candy-icons#374]
As the title suggests, the icon for "Tutanota Desktop" remains the default one within the minimised panel. Every other iteration of said icon changes correctly. The same problem has been spotted both on Windows 10 and Manjaro.

![Tutanota Desktop - Error](https://user-images.githubusercontent.com/100699869/156184409-0f744c85-adc3-4e99-97e3-c845383b0cd9.png)

**Comment by ratijas** [comment]
Whoever you are, deleted user, you meant to say "system tray icon" instead of "minimized". And sadly not "Every other iteration of said icon changes correctly" — this heavily depends on implementation details of each and every application and the protocol they use to represent themself in systray in the first place. As such, there's nothing candy icons could do if an app is drawing graphics directly instead of requesting a named icon.

Closing because it is out of scope.
